# Generated by Django 5.0.6 on 2024-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="linkedin",),
        migrations.RemoveField(model_name="userprofile", name="twitter",),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile", name="website", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="exit", max_length=20),
            preserve_default=False,
        ),
    ]
