# Generated by Django 5.0.6 on 2024-08-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regi", "0003_userprofile_email_userprofile_name_userprofile_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="email",),
        migrations.RemoveField(model_name="userprofile", name="name",),
        migrations.RemoveField(model_name="userprofile", name="role",),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
